#!/usr/bin/env python3
"""Room migration chain check — RikkaMinis CI scan gate.

## Why this gate exists

The project keeps hand-written `MIGRATION_x_y` objects across two Room
databases (AppDatabase v12, ProviderDatabase v10). Hand-written migrations
have a silent failure mode:

  * a version bump without a migration  → runtime crash
    (IllegalStateException: "A migration from X to Y was required but not found")
  * a migration declared but never wired into `addMigrations(...)` → same
    crash, only for users who crossed that version
  * a migration with a non-contiguous step (e.g. Migration(4, 6)) → Room
    rejects the chain outright

A green unit test does not catch this: the tests pin the happy path, and the
schema validation only runs on a real device at open time. This gate makes
all three loud before the build stamps its artifacts green.

Checks (per database file):

  1. CHAIN   — `version = N` in @Database; every `Migration(A, B)` must step
     exactly one at a time, so `B == A+1` (upgrade) or `B == A-1`
     (downgrade); nothing in between. The set of UPGRADE steps must cover
     2..N exactly — version 1 is the initial schema generated by Room, so no
     migration targets it. No gap, no duplicate.
     Downgrade steps are excluded from the coverage test on purpose: their
     targets are lower than N and could otherwise mask a missing upgrade.
     (A `Migration(3, 2)` does not get anyone to version 3.)
  2. WIRED   — every declared `MIGRATION_A_B` must appear in an
     `addMigrations(...)` call in the same file; and nothing wired may lack a
     declaration.
  3. BOUNDS  — no DOWNGRADE migration may start above the database version:
     for `Migration(A, B)` with `B < A`, require `A <= N`.

Downgrade migrations are the point of [T-android-downgrade-compat]: they let
an OLDER APK open a database written by a NEWER one instead of throwing. The
downgrade branch in CHAIN keeps `Migration(13, 12)` from failing the build
with a bogus "non-contiguous step" (which is exactly how the gate would have
become an obstacle to the fix it should have protected), and BOUNDS stops it
becoming a real crash instead. Room's `MigrationManager.buildMap` walks the
registered list in order and throws `IllegalArgumentException` ("Invalid
migration ... Migrations must be chained. Starting from migration X, expected
a migration starting at version 12") for the first migration whose `from` is
neither already a known target nor the current walk head — and the walk tops
out at the database version. Verified against the bytecode of
`room-common:2.6.1`, the version this build pins (`MigrationManager.buildMap`,
invoked from `RoomOpenHelper`'s constructor). So `Migration(13, 12)` cannot
exist in a `version = 12` build at all: it would crash every launch, for every
user, on a database that was never downgraded. A downgrade pair can only ship
with the bump that creates its `from` version.

## Why entity-column coverage is NOT checked here (design note)

A third natural check — "every @Entity column appears in some migration SQL" —
is **not implementable from source alone** in this repo: `exportSchema = false`
means Room never emits schema JSON, and the v1 CREATE TABLE statements are
generated from the entities *as they were at v1*, which no longer exist
anywhere in the tree. A source-level column check therefore produces only
false positives (every v1 column is flagged as "not in any migration") — a
check with 20+ false positives is worse than no check.

The correct home for that check is an `androidTest` using Room's
`MigrationTestHelper` with `exportSchema = true` (which records every schema
version as JSON). That needs an Android instrumented runner — a separate
investment, not a scan-gate-sized change. Until then, the honest guard for
"added a column but forgot the migration" is the four-way-sync discipline
(`four_way_sync_check.py`) plus this chain check.

Usage:
  python3 scripts/scan/room_migration_check.py <repo_root>
  python3 scripts/scan/room_migration_check.py --self-test

Exit: 0 = clean, 1 = violation(s) found.
"""

import os
import re
import sys

DB_DIR = "src/android/app/src/main/java/com/rikkaminis/app/data/db"
DATABASES = ["AppDatabase.kt", "ProviderDatabase.kt"]

VERSION_RE = re.compile(r"@Database\s*\((.*?)\)\s*(?:abstract\s+)?class", re.S)
MIG_DECL_RE = re.compile(
    r"val\s+(MIGRATION_\d+_\d+)\s*=\s*object\s*:\s*Migration\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)"
)
WIRED_RE = re.compile(r"addMigrations\s*\(([^)]*)\)", re.S)

PASS = 0
FAIL = 0


def check(name, ok, detail=""):
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"  ✅ {name}")
        return True
    FAIL += 1
    print(f"  ❌ {name}" + (f"\n     {detail}" if detail else ""))
    return False


def parse_database(src):
    """Return (version, {MIGRATION_name: (a, b)})."""
    m = VERSION_RE.search(src)
    version = int(re.search(r"version\s*=\s*(\d+)", m.group(1)).group(1)) if m else None
    decls = {}
    for name, a, b in MIG_DECL_RE.findall(src):
        decls[name] = (int(a), int(b))
    return version, decls


def parse_wired(src):
    names = set()
    for block in WIRED_RE.findall(src):
        for m in re.findall(r"MIGRATION_\d+_\d+", block):
            names.add(m)
    return names


def check_db(path):
    """Return (problems, info) for one database file."""
    src = open(path, encoding="utf-8").read()
    problems = []
    name = os.path.basename(path)
    version, decls = parse_database(src)
    if version is None:
        return [f"{name}: no @Database version found"], {}
    if not decls:
        return [f"{name}: version={version} but zero Migration declarations"], {}

    # 0. NAME vs PAIR.
    #
    # A comment that merely mentions "MIGRATION_12_13" is not a declaration
    # (MIG_DECL_RE requires the `val X = object : Migration(...)` shape), so
    # prose can never trip the WIRED check below. But a DECLARATION whose name
    # disagrees with the step it performs compiles fine and silently reverses
    # the wrong way: name MIGRATION_12_13 with Migration(12, 11) would ship
    # under the wrong pair and no other check would see it.
    for mig, (a, b) in sorted(decls.items()):
        if mig != f"MIGRATION_{a}_{b}":
            problems.append(
                f"{name}: {mig} = Migration({a}, {b}) — the name disagrees with the "
                f"step it performs (expected Migration({a}, {a + 1}) or Migration({a}, {a - 1}))"
            )

    # 1. CHAIN contiguity.
    #
    # A step is legal iff it moves exactly one version: +1 upgrades a database,
    # -1 downgrades it. Anything else (Migration(4, 6)) Room rejects outright.
    upgrades = {}
    downgrades = {}
    illegal = []
    for mig, (a, b) in sorted(decls.items()):
        if b == a + 1:
            upgrades[mig] = (a, b)
        elif b == a - 1:
            downgrades[mig] = (a, b)
        else:
            illegal.append((mig, a, b))
    for mig, a, b in illegal:
        problems.append(
            f"{name}: {mig} = Migration({a}, {b}) — non-contiguous step; a migration "
            f"must step exactly one version (upgrade {a} -> {a + 1} or downgrade {a} -> {a - 1})"
        )

    # 1b. BOUNDS — a downgrade cannot START above the database version.
    #
    # Room's MigrationManager.buildMap walks the list in order and throws
    # IllegalArgumentException("Invalid migration ... Migrations must be chained.
    # ... expected a migration starting at version N") for the first migration
    # whose `from` is neither already a known target nor the walk head — and
    # the walk tops out at N, because no legal migration targets past it (an
    # upgrade ending above N is already rejected above). So Migration(13, 12)
    # is unregistrable in a `version = 12` build: it crashes every launch, for
    # every user, on a database that was never downgraded. Room-common 2.6.1
    # bytecode, the version this build pins. Downgrades ship with the bump
    # that creates their `from` version.
    for mig, (a, b) in sorted(downgrades.items()):
        if a > version:
            problems.append(
                f"{name}: {mig} = Migration({a}, {b}) — a downgrade may not start above "
                f"@Database version {version}; Room rejects the whole chain at build time "
                f'(IllegalArgumentException "Migrations must be chained"), crashing every '
                f"launch. Ship it with the bump that reaches version {a}"
            )

    # Coverage is measured against UPGRADES ONLY. A downgrade's target is
    # below N and could mask a missing upgrade — a Migration(3, 2) does not
    # get any user to version 3. Version 1 is Room's initial schema, so no
    # migration targets it and coverage is required for 2..N only.
    covered = {b for (_a, b) in upgrades.values()}
    missing = [v for v in range(2, version + 1) if v not in covered]
    if missing:
        problems.append(
            f"{name}: version={version} but migration chain misses target version(s) {missing} "
            f"— a user upgrading across that gap hits IllegalStateException at open time"
        )

    # No separate "duplicate target" check: the migration name IS its version
    # pair (MIGRATION_A_B), so two distinct names cannot share a (source,
    # target) pair, and a repeated name is already a Kotlin compile error. A
    # cross-direction pair sharing a target (MIGRATION_11_12 and
    # MIGRATION_13_12 both ending at 12) is correct by construction.

    # 2. WIRED
    wired = parse_wired(src)
    unwired = sorted(set(decls) - wired)
    if unwired:
        problems.append(
            f"{name}: declared but NOT wired into addMigrations(...): {unwired} "
            f"— users crossing that version crash at open time"
        )
    ghost = sorted(wired - set(decls))
    if ghost:
        problems.append(f"{name}: wired into addMigrations(...) but no declaration found: {ghost}")

    return problems, {
        "version": version,
        "migrations": len(decls),
        "upgrades": len(upgrades),
        "downgrades": len(downgrades),
    }


def self_test():
    import tempfile
    ok = True
    header = '''package com.rikkaminis.app.data.db
import androidx.room.*
@Database(entities = [Foo::class], version = 3)
abstract class AppDatabase : RoomDatabase() {
    companion object {
        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN a TEXT")
            }
        }
'''
    build = 'fun build() = builder().addMigrations({WIRED}).build()'
    trailer = '''    }
}
@Entity(tableName = "foos")
data class Foo(@PrimaryKey val id: String, @ColumnInfo(name = "a") val a: String?)
'''

    def make(migrations_block, wired, version=3):
        src = (header.replace("version = 3", f"version = {version}")
               + migrations_block
               + build.replace("{WIRED}", wired) + "\n" + trailer)
        root = tempfile.mkdtemp(prefix="mig-")
        d = os.path.join(root, DB_DIR)
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, "AppDatabase.kt"), "w").write(src)
        return check_db(os.path.join(d, "AppDatabase.kt"))

    # dirty A: version bumped to 3 but MIGRATION_2_3 never wired
    probs, _ = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2",
    )
    ok &= check(f"self-test: unwired migration CATCHES ({len(probs)} problem(s))", len(probs) > 0, str(probs))
    ok &= check("self-test: problem names MIGRATION_2_3", any("MIGRATION_2_3" in p for p in probs), str(probs))

    # dirty B: non-contiguous step
    probs2, _ = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 5) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3",
    )
    ok &= check("self-test: non-contiguous step CATCHES", any("non-contiguous" in p for p in probs2), str(probs2))

    # dirty C: the declaration name lies about the step. Compiles fine, and
    # the WIRED check cannot catch it because both sides use the same name.
    probs2b, _ = make(
        '''        val MIGRATION_2_5 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_5",
    )
    ok &= check(
        "self-test: name/pair mismatch CATCHES",
        any("name disagrees" in p for p in probs2b),
        str(probs2b),
    )

    # prose: a comment that only MENTIONS a migration name is not a
    # declaration, so it must not be demanded in addMigrations(...). This is
    # what lets the real AppDatabase.kt document MIGRATION_12_13 / _12_11
    # that do not exist yet.
    probs2c, _ = make(
        '''        // Superseded by MIGRATION_9_10 below; kept for history.
        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3",
    )
    ok &= check("self-test: prose mention of an unwritten migration is IGNORED", len(probs2c) == 0, str(probs2c))

    # dirty D: Room cannot register a downgrade that starts above the database
    # version — the walk in MigrationManager.buildMap never reaches `from`.
    probs2d, _ = make(
        '''        val MIGRATION_4_3 = object : Migration(4, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // empty body is fine; the registration is what is rejected
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3, MIGRATION_4_3",
        version=3,
    )
    ok &= check(
        "self-test: downgrade starting above the db version CATCHES",
        any("may not start above" in p for p in probs2d),
        str(probs2d),
    )

    # clean
    probs3, inf = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3",
    )
    ok &= check("self-test: clean fixture passes", len(probs3) == 0, str(probs3))
    ok &= check("self-test: clean fixture reports version=3 migrations=2", inf.get("version") == 3 and inf.get("migrations") == 2, str(inf))

    # A downgrade migration is legal (T-android-downgrade-compat) and must be
    # reported, not rejected — this is the regression that blocked the real
    # fix: the gate used to call Migration(3, 2) "non-contiguous".
    probs4, inf4 = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
        val MIGRATION_3_2 = object : Migration(3, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // no-op downgrade
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_2",
    )
    ok &= check("self-test: downgrade migration is ACCEPTED", len(probs4) == 0, str(probs4))
    ok &= check(
        "self-test: downgrade counted separately from upgrades",
        inf4.get("upgrades") == 2 and inf4.get("downgrades") == 1 and inf4.get("migrations") == 3,
        str(inf4),
    )

    # A downgrade must NOT paper over a missing upgrade. Version 4 needs an
    # upgrade path to 4; a Migration(4, 3) only walks the other way.
    probs5, _ = make(
        '''        val MIGRATION_4_3 = object : Migration(4, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // no-op downgrade
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_4_3",
        version=4,
    )
    ok &= check(
        "self-test: downgrade does not mask a missing upgrade",
        any("misses target version(s)" in p for p in probs5),
        str(probs5),
    )

    # The two directions sharing a target is NOT a dupe — that is exactly
    # MIGRATION_11_12 / MIGRATION_13_12 both ending at 12.
    probs8, _ = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
        val MIGRATION_3_2 = object : Migration(3, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // no-op downgrade
            }
        }
        val MIGRATION_2_1 = object : Migration(2, 1) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // no-op downgrade
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_2, MIGRATION_2_1",
    )
    ok &= check("self-test: cross-direction same target is not a dupe", len(probs8) == 0, str(probs8))
    return 0 if ok else 1


def main():
    args = sys.argv[1:]
    if args and args[0] == "--self-test":
        return self_test()
    root = os.path.abspath(args[0] if args else ".")
    all_problems = []
    info = {}
    for db in DATABASES:
        p = os.path.join(root, DB_DIR, db)
        if not os.path.isfile(p):
            all_problems.append(f"database file not found: {p}")
            continue
        probs, inf = check_db(p)
        info[db] = inf
        all_problems.extend(probs)
    for db, inf in info.items():
        print(
            f"  {db}: version={inf.get('version')} migrations={inf.get('migrations')} "
            f"(upgrades={inf.get('upgrades')} downgrades={inf.get('downgrades')})"
        )
    if all_problems:
        print(f"❌ Room migration check: {len(all_problems)} problem(s)")
        for x in all_problems:
            print("     " + x)
        return 1
    print("✅ Room migration check: upgrade chain contiguous (2..N), every step ±1, "
          "all declared migrations wired")
    return 0


if __name__ == "__main__":
    sys.exit(main())
