#!/usr/bin/env python3
"""Room migration chain check — RikkaMinis CI scan gate.

## Why this gate exists

The project keeps 26 hand-written `MIGRATION_x_y` objects across two Room
databases (AppDatabase v12, ProviderDatabase v10). Hand-written migrations
have a silent failure mode:

  * a version bump without a migration  → runtime crash
    (IllegalStateException: "A migration from X to Y was required but not found")
  * a migration declared but never wired into `addMigrations(...)` → same
    crash, only for users who crossed that version
  * a migration with a non-contiguous step (e.g. Migration(4, 6)) → Room
    rejects the chain outright

A green unit test does not catch this: the tests pin the happy path, and the
schema validation only runs on a real device at open time. This gate makes
all three loud before the build stamps its artifacts green.

Checks (per database file):

  1. CHAIN  — `version = N` in @Database; every `Migration(A, B)` must satisfy
     B == A+1 and the set must cover 2..N exactly (version 1 is the initial
     schema generated by Room; no migration targets it). No gap, no duplicate.
  2. WIRED  — every declared `MIGRATION_A_B` must appear in an
     `addMigrations(...)` call in the same file; and nothing wired may lack a
     declaration.

## Why entity-column coverage is NOT checked here (design note)

A third natural check — "every @Entity column appears in some migration SQL" —
is **not implementable from source alone** in this repo: `exportSchema = false`
means Room never emits schema JSON, and the v1 CREATE TABLE statements are
generated from the entities *as they were at v1*, which no longer exist
anywhere in the tree. A source-level column check therefore produces only
false positives (every v1 column is flagged as "not in any migration") — a
check with 20+ false positives is worse than no check.

The correct home for that check is an `androidTest` using Room's
`MigrationTestHelper` with `exportSchema = true` (which records every schema
version as JSON). That needs an Android instrumented runner — a separate
investment, not a scan-gate-sized change. Until then, the honest guard for
"added a column but forgot the migration" is the four-way-sync discipline
(`four_way_sync_check.py`) plus this chain check.

Usage:
  python3 scripts/scan/room_migration_check.py <repo_root>
  python3 scripts/scan/room_migration_check.py --self-test

Exit: 0 = clean, 1 = violation(s) found.
"""

import os
import re
import sys

DB_DIR = "src/android/app/src/main/java/com/rikkaminis/app/data/db"
DATABASES = ["AppDatabase.kt", "ProviderDatabase.kt"]

VERSION_RE = re.compile(r"@Database\s*\((.*?)\)\s*(?:abstract\s+)?class", re.S)
MIG_DECL_RE = re.compile(
    r"val\s+(MIGRATION_\d+_\d+)\s*=\s*object\s*:\s*Migration\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)"
)
WIRED_RE = re.compile(r"addMigrations\s*\(([^)]*)\)", re.S)

PASS = 0
FAIL = 0


def check(name, ok, detail=""):
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"  ✅ {name}")
        return True
    FAIL += 1
    print(f"  ❌ {name}" + (f"\n     {detail}" if detail else ""))
    return False


def parse_database(src):
    """Return (version, {MIGRATION_name: (a, b)})."""
    m = VERSION_RE.search(src)
    version = int(re.search(r"version\s*=\s*(\d+)", m.group(1)).group(1)) if m else None
    decls = {}
    for name, a, b in MIG_DECL_RE.findall(src):
        decls[name] = (int(a), int(b))
    return version, decls


def parse_wired(src):
    names = set()
    for block in WIRED_RE.findall(src):
        for m in re.findall(r"MIGRATION_\d+_\d+", block):
            names.add(m)
    return names


def check_db(path):
    """Return (problems, info) for one database file."""
    src = open(path, encoding="utf-8").read()
    problems = []
    name = os.path.basename(path)
    version, decls = parse_database(src)
    if version is None:
        return [f"{name}: no @Database version found"], {}
    if not decls:
        return [f"{name}: version={version} but zero Migration declarations"], {}

    # 1. CHAIN contiguity — version 1 is Room's initial schema, no migration
    # targets it, so coverage is required for 2..N only.
    for mig, (a, b) in sorted(decls.items()):
        if b != a + 1:
            problems.append(
                f"{name}: {mig} = Migration({a}, {b}) — non-contiguous step (expected {a} -> {a + 1})"
            )
    covered = {b for (_a, b) in decls.values()}
    missing = [v for v in range(2, version + 1) if v not in covered]
    if missing:
        problems.append(
            f"{name}: version={version} but migration chain misses target version(s) {missing} "
            f"— a user upgrading across that gap hits IllegalStateException at open time"
        )
    dupes = {}
    for mig, (a, b) in decls.items():
        dupes.setdefault(b, []).append(mig)
    for b, migs in sorted(dupes.items()):
        if len(migs) > 1:
            problems.append(f"{name}: duplicate migration target {b}: {migs}")

    # 2. WIRED
    wired = parse_wired(src)
    unwired = sorted(set(decls) - wired)
    if unwired:
        problems.append(
            f"{name}: declared but NOT wired into addMigrations(...): {unwired} "
            f"— users crossing that version crash at open time"
        )
    ghost = sorted(wired - set(decls))
    if ghost:
        problems.append(f"{name}: wired into addMigrations(...) but no declaration found: {ghost}")

    return problems, {"version": version, "migrations": len(decls)}


def self_test():
    import tempfile
    ok = True
    header = '''package com.rikkaminis.app.data.db
import androidx.room.*
@Database(entities = [Foo::class], version = 3)
abstract class AppDatabase : RoomDatabase() {
    companion object {
        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN a TEXT")
            }
        }
'''
    build = 'fun build() = builder().addMigrations({WIRED}).build()'
    trailer = '''    }
}
@Entity(tableName = "foos")
data class Foo(@PrimaryKey val id: String, @ColumnInfo(name = "a") val a: String?)
'''

    def make(migrations_block, wired):
        src = header + migrations_block + build.replace("{WIRED}", wired) + "\n" + trailer
        root = tempfile.mkdtemp(prefix="mig-")
        d = os.path.join(root, DB_DIR)
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, "AppDatabase.kt"), "w").write(src)
        return check_db(os.path.join(d, "AppDatabase.kt"))

    # dirty A: version bumped to 3 but MIGRATION_2_3 never wired
    probs, _ = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2",
    )
    ok &= check(f"self-test: unwired migration CATCHES ({len(probs)} problem(s))", len(probs) > 0, str(probs))
    ok &= check("self-test: problem names MIGRATION_2_3", any("MIGRATION_2_3" in p for p in probs), str(probs))

    # dirty B: non-contiguous step
    probs2, _ = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 5) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3",
    )
    ok &= check("self-test: non-contiguous step CATCHES", any("non-contiguous" in p for p in probs2), str(probs2))

    # clean
    probs3, inf = make(
        '''        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE foos ADD COLUMN b TEXT")
            }
        }
''',
        "MIGRATION_1_2, MIGRATION_2_3",
    )
    ok &= check("self-test: clean fixture passes", len(probs3) == 0, str(probs3))
    ok &= check("self-test: clean fixture reports version=3 migrations=2", inf.get("version") == 3 and inf.get("migrations") == 2, str(inf))
    return 0 if ok else 1


def main():
    args = sys.argv[1:]
    if args and args[0] == "--self-test":
        return self_test()
    root = os.path.abspath(args[0] if args else ".")
    all_problems = []
    info = {}
    for db in DATABASES:
        p = os.path.join(root, DB_DIR, db)
        if not os.path.isfile(p):
            all_problems.append(f"database file not found: {p}")
            continue
        probs, inf = check_db(p)
        info[db] = inf
        all_problems.extend(probs)
    for db, inf in info.items():
        print(f"  {db}: version={inf.get('version')} migrations={inf.get('migrations')}")
    if all_problems:
        print(f"❌ Room migration check: {len(all_problems)} problem(s)")
        for x in all_problems:
            print("     " + x)
        return 1
    print("✅ Room migration check: chains contiguous (2..N), all declared migrations wired")
    return 0


if __name__ == "__main__":
    sys.exit(main())
